services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
      - redis

  composer:
    image: composer:latest
    container_name: composer_install
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: install
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_laravel
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_queue
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan queue:work
    depends_on:
      - app
      - redis
      - db
    networks:
      - laravel

  frontend:
    image: node:18-alpine
    container_name: angular_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start"
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
